#' Mplot for Meta data generated by METAL
#' MarkerName : eg. 1:10086:A/C or 1:10086:A:C
#' Usage eg. Mplot_for_Meta('/A/B/C','a.TBL','/a/b/c','plotA',10)
#' @param file_path the pathway of meta file
#' @param file_name the name of of meta file with suffix
#' @param figure_pathy the pathway to save Mplot
#' @param figure_name the name of of Mplot
#' @param p_col column number of p-value
#' @param snp_col column number of MarkerName
#' @param colour color of Mplot
#' @export



Mplot_for_QTLs <- function(file_path,file_name,qtl_file,figure_pathy,figure_name,p_col,snp_col,colour){

  requireNamespace(library(CMplot))

  library(data.table)

  dat1 <- data.table::fread(paste0(file_path,'/',file_name))
  names(dat1)[p_col] <- 'pvalue'
  names(dat1)[snp_col] <- 'MarkerName'
  dat1$CHR <- sapply(strsplit(dat1$MarkerName,':'),'[',1)
  dat1$BP <- sapply(strsplit(dat1$MarkerName,':'),'[',2)
  dat_plot1 <- dat1[,c('MarkerName','CHR','BP','pvalue')]
  names(dat_plot1) <- c('SNP','Chromosome','Position',figure_name)

  qtl <- data.table::fread(qtl_file)
  dat_plot1 <- subset(dat_plot1,dat_plot1$SNP%in%qtl$variant_id)

  # cols=c("black","orange","grey")
  cols=colour
  setwd(figure_pathy)

  CMplot::CMplot(dat_plot1,plot.type="m",LOG10=TRUE,threshold.lwd=c(1,1), threshold.col='#BC3C29',main.font=1,ylab=expression(-log[10](italic(P))),
                 threshold=0.05,threshold.lty=c(1,2),chr.den.col=NULL,col = cols,cex =c(0.5,0.5,0.5),lab.font=1,main="Chromosome",height = 4,width = 8.5,
                 amplify= TRUE, signal.cex=0.5, file="pdf",dpi=300,file.output=TRUE,verbose=TRUE,legend.pos='middle')
  cat(paste0('+++---------------------------------- Mplot of *** ',figure_name,' *** has been drawn! ----------------------------------+++'))
}

