#' Mplot for Meta data generated by METAL
#' MarkerName : eg. 1:10086:A/C or 1:10086:A:C
#' Usage eg. Mplot_for_Meta('/A/B/C','a.TBL','/a/b/c','plotA',10)
#' @param file_path the pathway of meta file
#' @param file_name the name of of meta file with suffix
#' @param figure_pathy the pathway to save Mplot
#' @param figure_name the name of of Mplot
#' @param p_col column number of p-value
#' @param colour color of Mplot
#' @export



Mplot_for_Meta <- function(file_path,file_name,figure_pathy,figure_name,p_col,colour){

library(CMplot)
library(data.table)

dat1 <- data.table::fread(paste0(file_path,'/',file_name))
names(dat1)[p_col] <- 'pvalue'
dat1$CHR <- sapply(strsplit(dat1$MarkerName,':'),'[',1)
dat1$BP <- sapply(strsplit(dat1$MarkerName,':'),'[',2)
dat_plot1 <- dat1[,c('MarkerName','CHR','BP','pvalue')]
names(dat_plot1) <- c('SNP','Chromosome','Position',figure_name)
# cols=c("black","orange","grey")
cols=colour

setwd(figure_pathy)

cat('+++---------------------------------- Mplot is drawing now ----------------------------------+++')
CMplot::CMplot(dat_plot1,plot.type="m",LOG10=TRUE,threshold.lwd=c(1,1), threshold.col=c("red","black"),
       threshold=c(5e-08,5e-06),threshold.lty=c(1,2),chr.den.col=NULL,col = cols,cex =c(0.5,0.5,0.5),
       amplify= TRUE, signal.cex=0.5, file="jpg",dpi=300,file.output=TRUE,verbose=TRUE)

print('+++---------------------------------- Mplot has been drawn ----------------------------------+++')

}

