#' Mplot for TWAS results generated by FUSION
#' Usage eg. Mplot_for_TWAS('/A/B/C','Lung_China_Intron_twasplot_update','TWAS Manhattan Plot of NSCLC','0.1','/A/B/C',11)
#' @param file_path the pathway of TWAS result file
#' @param file_name the name of of TWAS result file with suffix
#' @param outDir the pathway to save Mplot
#' @param title the name and title of of Mplot
#' @param Sig_FDR_Thresh Significant FDR threshold of TWAS results
#' @param color_scheme Color scheme of Mplot including 15 schemes
#' @export



Mplot_for_TWAS <- function(file_path,file_name,title,Sig_FDR_Thresh,outDir,color_scheme){

  suppressMessages(library(data.table))
  suppressMessages(library(ggrepel))
  suppressMessages(library(ggplot2))
  suppressMessages(library(cowplot))

  TWAS_manhattan = function(dataframe, title=title, color=color,ylimit=max(-log10(d$TWAS.P),na.rm=T)+1) {

    d=dataframe[order(dataframe$CHR, dataframe$P0),]
    d=d[!is.na(d$TWAS.P),]
    d=d[!is.na(d$TWAS.FDR),]

    d$pos=0
    ticks=NULL
    lastbase=0
    numchroms=length(unique(d$CHR))

    for (i in unique(d$CHR)) {
      if (i==1) {
        d[d$CHR==i, ]$pos=d[d$CHR==i, ]$P0
      }	else {
        lastbase=lastbase+tail(subset(d,CHR==i-1)$P0, 1)
        d[d$CHR==i, ]$pos=d[d$CHR==i, ]$P0+lastbase
      }
      ticks=c(ticks, d[d$CHR==i, ]$pos[floor(length(d[d$CHR==i, ]$pos)/2)+1])
    }

    ticklim=c(min(d$pos),max(d$pos))

    mycols=rep(color,60)

    d_sig_all<-d[which(abs(d$TWAS.FDR) < Sig_FDR_Thresh),]
    d_sig_all<-d_sig_all[order(d_sig_all$TWAS.FDR),]
    d_sig<-d_sig_all[!duplicated(d_sig_all$ID),]
    # d_sig_all_left <- d_sig_all[!rownames(d_sig_all)%in%rownames(d_sig),]
    d_no_sig<-d[which(abs(d$TWAS.FDR) >= Sig_FDR_Thresh),]
    if(!nrow(d_sig_all)==0){
      sig_level <- mean(c(min(-log10(d_sig_all$TWAS.P)),max(-log10(d_no_sig$TWAS.P))))
    }else{
      sig_level <- NULL
    }

    chr_labs<-as.character(unique(d$CHR))

    if(dim(d_sig)[1] == 0){
      p<-ggplot(d,aes(x=pos,y=-log10(d$TWAS.P),colour=factor(CHR))) +
        geom_point(size=3) +
        scale_x_continuous(name="Chromosome", breaks=ticks, labels=chr_labs) +
        scale_y_continuous(name=bquote(-"log"[10]("p-value")),limits=c(0,ylimit)) +
        scale_colour_manual(values=mycols, guide=FALSE) +
        geom_hline(yintercept=sig_level,colour="black",linetype='dashed',size=1.5)

    } else {

      p<-ggplot(d_no_sig,aes(x=pos,y=-log10(d_no_sig$TWAS.P),colour=factor(CHR))) +
        geom_point(size=3) +
        scale_x_continuous(name="Chromosome", breaks=ticks, labels=chr_labs) +
        scale_y_continuous(name=bquote(-"log"[10]("p-value")),limits=c(0,ylimit)) +
        scale_colour_manual(values=mycols, guide=FALSE) +
        geom_hline(yintercept=sig_level,colour="black",linetype='dashed',size=1.5) +
        geom_point(data=d_sig, aes(x=pos,y=-log10(d_sig$TWAS.P)), colour="#F98232", fill='#F98232', size=3) +
        geom_point(data=d_sig, aes(x=pos,y=-log10(d_sig$TWAS.P)), colour="#DC0000B2", fill='#DC0000B2', size=3)

      p<-p+geom_text_repel(data=d_sig, aes(x=pos,y=-log10(d_sig$TWAS.P), label=ID),
                           colour='black', nudge_y=1, size=3.5, force=5, segment.alpha=0.25, ylim=c(sig_level+0.1,NA))
    }

    p<-p +
      ggtitle(title) + # 添加标题
      theme(
        axis.text.x = element_text(size=14),
        plot.title = element_text(hjust=0.5, size=14),
        panel.border = element_rect(colour = "black", fill=NA, size=1),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black")
      )
    pdf(paste0(outDir,'/',title,'.pdf'), width = 12, height = 8)
    print(p)
    dev.off()
  }

  colors <- list(
    colors_1 = c('#44B5AD','#3A948E','#36807A','#2f615d'),
    colors_2 = c("#8E9A9A", "#B2A7A5", "#D9B8C4", "#E6E2E2"),
    colors_3 = c("#355C7D", "#C06C84", "#DAA520", "#A9A9A9"),
    colors_4 = c("#1F77B4", "#FFDAB9", "#AEC7E8", "#98DF8A"),
    colors_5 = c("#A3B1C6", "#C1A3B1", "#D4A59A", "#E4E1E1"),
    colors_6 = c("#778899", "#B0C4DE", "#D4A59A", "#E6E6FA"),
    colors_7 = c("#795548", "#FFD1DC", "#AED6F1", "#FDFD96"),
    colors_8 = c("#5DADE2", "#45B39D", "#EAECEE", "#AED6F1"),
    colors_9 = c("#A3B1C6", "#C1A3B1", "#D4A59A", "#E4E1E1"),
    colors_10 = c("#8B4513", "#DAA520", "#4CAF50", "#F5F5DC"),
    colors_11 = c("#D8980B","#194a55","#187c65","#c29f62","#83ba9e"),
    colors_12 = c("#023f75","#46b6bc","#266b69","#cc805e","#f6c619"),
    colors_13 = c("#fa6e01","#2f2f2f","#63211c","#e6a84b","#ff717f"),
    colors_14 = c("#223e9c","#63211c","#aebea6","#edae11","#0f6657"),
    colors_15 = c("#6a73cf","#edd064","#0eb0c8","#f2ccac","#a1d5b9","#e1abbc")
  )

  # Read in the TWAS data
  twas<-data.frame(fread(paste0(file_path,'/',file_name)))
  title=title
  # Sig_FDR_Thresh=Sig_FDR_Thresh

  # Make plot
  # pdf(paste0(outDir,'/',title,'.pdf'), width = 12, height = 8)
  TWAS_manhattan(dataframe=twas,title=title,color=colors[[color_scheme]])
  # dev.off()

  cat(paste0('+++---------------------------------- Mplot of *** ',title,' with color scheme ',color_scheme,' *** has been drawn! ----------------------------------+++\n'))

}
